//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectAvalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Auto copiar.
        /// </summary>
        public static string AutoCopyBehaviorLabel {
            get {
                return ResourceManager.GetString("AutoCopyBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Baixar versão mais atual automaticamente.
        /// </summary>
        public static string AutoDownloadLabel {
            get {
                return ResourceManager.GetString("AutoDownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Auto colar.
        /// </summary>
        public static string AutoPasteBehaviorLabel {
            get {
                return ResourceManager.GetString("AutoPasteBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tema Noturno.
        /// </summary>
        public static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativar Renderização por GPU.
        /// </summary>
        public static string EnabledGPULabel {
            get {
                return ResourceManager.GetString("EnabledGPULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quando a placa de video(GPU) está habilitada para renderizar a interface de usuário(UI). Usar a GPU ao invés da CPU pode melhor a performance..
        /// </summary>
        public static string EnabledGPUTooltip {
            get {
                return ResourceManager.GetString("EnabledGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Manter aplicativo rodando em background.
        /// </summary>
        public static string onClosedBehaviorLabel {
            get {
                return ResourceManager.GetString("onClosedBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciar o aplicativo juntamente ao Windows.
        /// </summary>
        public static string onStartupBehaviorLabel {
            get {
                return ResourceManager.GetString("onStartupBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reiniciar o aplicativo.
        /// </summary>
        public static string RestartAppLabel {
            get {
                return ResourceManager.GetString("RestartAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As modificações serão aplicadas após o aplicativo ser reiniciado..
        /// </summary>
        public static string RestartNotificationLabel {
            get {
                return ResourceManager.GetString("RestartNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar aparência, e outras configurações.
        /// </summary>
        public static string SettingsPageCaption {
            get {
                return ResourceManager.GetString("SettingsPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Tema está sendo Alterarado... Aguarde....
        /// </summary>
        public static string ThemeChangingLabel {
            get {
                return ResourceManager.GetString("ThemeChangingLabel", resourceCulture);
            }
        }
    }
}
