//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectAvalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add New Checkbox.
        /// </summary>
        public static string Add_Checkbox_ToolTip {
            get {
                return ResourceManager.GetString("Add_Checkbox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Condition.
        /// </summary>
        public static string Add_Condition_ToolTip {
            get {
                return ResourceManager.GetString("Add_Condition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Item.
        /// </summary>
        public static string Add_Folder_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Add_Folder_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select an Item to Add to Project.
        /// </summary>
        public static string Add_Item_Dialog_Caption {
            get {
                return ResourceManager.GetString("Add_Item_Dialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add New Report Item.
        /// </summary>
        public static string Add_Item_ToolTip {
            get {
                return ResourceManager.GetString("Add_Item_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add New Law.
        /// </summary>
        public static string Add_Law_ToolTip {
            get {
                return ResourceManager.GetString("Add_Law_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add New Option.
        /// </summary>
        public static string Add_Option_ToolTip {
            get {
                return ResourceManager.GetString("Add_Option_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Options.
        /// </summary>
        public static string Add_Options_ToolTip {
            get {
                return ResourceManager.GetString("Add_Options_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Result.
        /// </summary>
        public static string Add_Result_ToolTip {
            get {
                return ResourceManager.GetString("Add_Result_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Rule.
        /// </summary>
        public static string Add_Rule_ToolTip {
            get {
                return ResourceManager.GetString("Add_Rule_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Solution Item.
        /// </summary>
        public static string Add_Solution_Item_Menu_Item {
            get {
                return ResourceManager.GetString("Add_Solution_Item_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add New Text Item.
        /// </summary>
        public static string Add_Text_Item_ToolTip {
            get {
                return ResourceManager.GetString("Add_Text_Item_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item name.
        /// </summary>
        public static string AddItemNameLabel {
            get {
                return ResourceManager.GetString("AddItemNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Advanced Settings.
        /// </summary>
        public static string AdvancedSettingsViewNavLabel {
            get {
                return ResourceManager.GetString("AdvancedSettingsViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Appearence.
        /// </summary>
        public static string AppearanceLabel {
            get {
                return ResourceManager.GetString("AppearanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Auto copy.
        /// </summary>
        public static string AutoCopyBehaviorLabel {
            get {
                return ResourceManager.GetString("AutoCopyBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download latest version automatically.
        /// </summary>
        public static string AutoDownloadLabel {
            get {
                return ResourceManager.GetString("AutoDownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Auto paste.
        /// </summary>
        public static string AutoPasteBehaviorLabel {
            get {
                return ResourceManager.GetString("AutoPasteBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        public static string CancelActionLabel {
            get {
                return ResourceManager.GetString("CancelActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Topic.
        /// </summary>
        public static string CheckboxContainerTopicLabel {
            get {
                return ResourceManager.GetString("CheckboxContainerTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Topic.
        /// </summary>
        public static string CheckboxItemTopicLabel {
            get {
                return ResourceManager.GetString("CheckboxItemTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        public static string CheckboxItemValueLabel {
            get {
                return ResourceManager.GetString("CheckboxItemValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company Address.
        /// </summary>
        public static string Company_Address_Watermark {
            get {
                return ResourceManager.GetString("Company_Address_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company Logo Path.
        /// </summary>
        public static string Company_Logo_FilePath_Watermark {
            get {
                return ResourceManager.GetString("Company_Logo_FilePath_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company Name.
        /// </summary>
        public static string Company_Name_Watermark {
            get {
                return ResourceManager.GetString("Company_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conditions.
        /// </summary>
        public static string Conditions_Label {
            get {
                return ResourceManager.GetString("Conditions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm.
        /// </summary>
        public static string ConfirmActionLabel {
            get {
                return ResourceManager.GetString("ConfirmActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continue.
        /// </summary>
        public static string ContinueActionLabel {
            get {
                return ResourceManager.GetString("ContinueActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark Mode.
        /// </summary>
        public static string DarkModeLabel {
            get {
                return ResourceManager.GetString("DarkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night Mode.
        /// </summary>
        public static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete Image.
        /// </summary>
        public static string Delete_Image_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Delete_Image_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turn on GPU Acceleration.
        /// </summary>
        public static string EnabledGPULabel {
            get {
                return ResourceManager.GetString("EnabledGPULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When the GPU Acceleration is enabled to render the UI. Using the GPU instead of CPU may improve performance..
        /// </summary>
        public static string EnabledGPUTooltip {
            get {
                return ResourceManager.GetString("EnabledGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude Condition.
        /// </summary>
        public static string Exclude_Condition_ToolTip {
            get {
                return ResourceManager.GetString("Exclude_Condition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude File.
        /// </summary>
        public static string Exclude_File_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Exclude_File_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude Folder.
        /// </summary>
        public static string Exclude_Folder_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Exclude_Folder_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude Result.
        /// </summary>
        public static string Exclude_Result_ToolTip {
            get {
                return ResourceManager.GetString("Exclude_Result_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude Rule.
        /// </summary>
        public static string Exclude_Rule_ToolTip {
            get {
                return ResourceManager.GetString("Exclude_Rule_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Folder Name.
        /// </summary>
        public static string Folder_Name_Watermark {
            get {
                return ResourceManager.GetString("Folder_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General Settings.
        /// </summary>
        public static string GeneralSettingsViewNavLabel {
            get {
                return ResourceManager.GetString("GeneralSettingsViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generate PDF.
        /// </summary>
        public static string Generate_Document_ToolTip {
            get {
                return ResourceManager.GetString("Generate_Document_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report Items.
        /// </summary>
        public static string ItemFormDataLabel {
            get {
                return ResourceManager.GetString("ItemFormDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Law Content.
        /// </summary>
        public static string ItemLawItemContentLabel {
            get {
                return ResourceManager.GetString("ItemLawItemContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Law ID.
        /// </summary>
        public static string ItemLawItemIdLabel {
            get {
                return ResourceManager.GetString("ItemLawItemIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Laws.
        /// </summary>
        public static string ItemLawItemsLabel {
            get {
                return ResourceManager.GetString("ItemLawItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item Name.
        /// </summary>
        public static string ItemNameLabel {
            get {
                return ResourceManager.GetString("ItemNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report Items.
        /// </summary>
        public static string Items_Label {
            get {
                return ResourceManager.GetString("Items_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select a Language.
        /// </summary>
        public static string LanguageSelectorLabel {
            get {
                return ResourceManager.GetString("LanguageSelectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Law Content.
        /// </summary>
        public static string Law_Body_Watermark {
            get {
                return ResourceManager.GetString("Law_Body_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Law Id.
        /// </summary>
        public static string Law_Id_Watermark {
            get {
                return ResourceManager.GetString("Law_Id_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Laws.
        /// </summary>
        public static string Laws_Label {
            get {
                return ResourceManager.GetString("Laws_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        public static string NextActionLabel {
            get {
                return ResourceManager.GetString("NextActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No Solution Open.
        /// </summary>
        public static string No_Solution_Open_Label {
            get {
                return ResourceManager.GetString("No_Solution_Open_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observations.
        /// </summary>
        public static string Observation_Label {
            get {
                return ResourceManager.GetString("Observation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observations.
        /// </summary>
        public static string Observation_Watermark {
            get {
                return ResourceManager.GetString("Observation_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Keep running the app on background.
        /// </summary>
        public static string onClosedBehaviorLabel {
            get {
                return ResourceManager.GetString("onClosedBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start app with windows.
        /// </summary>
        public static string onStartupBehaviorLabel {
            get {
                return ResourceManager.GetString("onStartupBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operation.
        /// </summary>
        public static string Operation_Label {
            get {
                return ResourceManager.GetString("Operation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        public static string Options_Label {
            get {
                return ResourceManager.GetString("Options_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Print.
        /// </summary>
        public static string Print_Document_ToolTip {
            get {
                return ResourceManager.GetString("Print_Document_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Print Document.
        /// </summary>
        public static string Print_Page_Title {
            get {
                return ResourceManager.GetString("Print_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Folder.
        /// </summary>
        public static string Project_Add_Folder_ToolBarItem {
            get {
                return ResourceManager.GetString("Project_Add_Folder_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Current Item.
        /// </summary>
        public static string Project_Item_Save_ToolBarItem {
            get {
                return ResourceManager.GetString("Project_Item_Save_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project Responsable.
        /// </summary>
        public static string Project_Responsable_Watermark {
            get {
                return ResourceManager.GetString("Project_Responsable_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project.
        /// </summary>
        public static string ProjectViewNavLabel {
            get {
                return ResourceManager.GetString("ProjectViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove Checkbox.
        /// </summary>
        public static string Remove_Checkbox_ToolTip {
            get {
                return ResourceManager.GetString("Remove_Checkbox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove Group.
        /// </summary>
        public static string Remove_Group_ToolTip {
            get {
                return ResourceManager.GetString("Remove_Group_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rename File.
        /// </summary>
        public static string Rename_File_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Rename_File_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rename Folder.
        /// </summary>
        public static string Rename_Folder_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Rename_Folder_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report Date.
        /// </summary>
        public static string Report_Date_Calendar_Header {
            get {
                return ResourceManager.GetString("Report_Date_Calendar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a State Code.
        /// </summary>
        public static string Report_State_Watermark {
            get {
                return ResourceManager.GetString("Report_State_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsable Email Address.
        /// </summary>
        public static string Responsable_Mail_Address_Watermark {
            get {
                return ResourceManager.GetString("Responsable_Mail_Address_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsable Phone Number.
        /// </summary>
        public static string Responsable_Phone_Number_Watermark {
            get {
                return ResourceManager.GetString("Responsable_Phone_Number_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart App.
        /// </summary>
        public static string RestartAppLabel {
            get {
                return ResourceManager.GetString("RestartAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The changes will be commited after restarting the application..
        /// </summary>
        public static string RestartNotificationLabel {
            get {
                return ResourceManager.GetString("RestartNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search Solution Item.
        /// </summary>
        public static string Search_Solution_Items_Watermark {
            get {
                return ResourceManager.GetString("Search_Solution_Items_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search settings / advanced features
        ///.
        /// </summary>
        public static string SearchBoxLabel {
            get {
                return ResourceManager.GetString("SearchBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Manages appearence, and other settings.
        /// </summary>
        public static string SettingsPageCaption {
            get {
                return ResourceManager.GetString("SettingsPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings.
        /// </summary>
        public static string SettingsPageLabel {
            get {
                return ResourceManager.GetString("SettingsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings.
        /// </summary>
        public static string SettingsViewNavLabel {
            get {
                return ResourceManager.GetString("SettingsViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a App is shutting down.
        /// </summary>
        public static string ShutdownDialogTitleLabel {
            get {
                return ResourceManager.GetString("ShutdownDialogTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setting everything down to finished the application..
        /// </summary>
        public static string ShutdownMessagePart1 {
            get {
                return ResourceManager.GetString("ShutdownMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It may take some time to be finished. Please, wait....
        /// </summary>
        public static string ShutdownMessagePart2 {
            get {
                return ResourceManager.GetString("ShutdownMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skip.
        /// </summary>
        public static string SkipActionLabel {
            get {
                return ResourceManager.GetString("SkipActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create Solution.
        /// </summary>
        public static string Solution_Create_ToolBarItem {
            get {
                return ResourceManager.GetString("Solution_Create_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solution Explorer.
        /// </summary>
        public static string Solution_Explorer_Label {
            get {
                return ResourceManager.GetString("Solution_Explorer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solution Location.
        /// </summary>
        public static string Solution_Folder_Watermark {
            get {
                return ResourceManager.GetString("Solution_Folder_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solution Name.
        /// </summary>
        public static string Solution_Name_Watermark {
            get {
                return ResourceManager.GetString("Solution_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open Solution.
        /// </summary>
        public static string Solution_Open_ToolBarItem {
            get {
                return ResourceManager.GetString("Solution_Open_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Print Solution.
        /// </summary>
        public static string Solution_Print_ToolBarItem {
            get {
                return ResourceManager.GetString("Solution_Print_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create New Report Template.
        /// </summary>
        public static string Template_Edit_Create_Item_ToolBarItem {
            get {
                return ResourceManager.GetString("Template_Edit_Create_Item_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open Report Template.
        /// </summary>
        public static string Template_Edit_Open_ToolBarItem {
            get {
                return ResourceManager.GetString("Template_Edit_Open_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Report Template.
        /// </summary>
        public static string Template_Edit_Save_Item_ToolBarItem {
            get {
                return ResourceManager.GetString("Template_Edit_Save_Item_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template.
        /// </summary>
        public static string Template_Tab_Header {
            get {
                return ResourceManager.GetString("Template_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template Edit.
        /// </summary>
        public static string TemplateEditViewNavLabel {
            get {
                return ResourceManager.GetString("TemplateEditViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Measurement unit.
        /// </summary>
        public static string TextBoxItemMeasurementUnitLabel {
            get {
                return ResourceManager.GetString("TextBoxItemMeasurementUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Topic.
        /// </summary>
        public static string TextBoxItemTopicLabel {
            get {
                return ResourceManager.GetString("TextBoxItemTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Theme is changing... Please Wait....
        /// </summary>
        public static string ThemeChangingLabel {
            get {
                return ResourceManager.GetString("ThemeChangingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark, Light, Theme.
        /// </summary>
        public static string ThemeKeyWords {
            get {
                return ResourceManager.GetString("ThemeKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Then.
        /// </summary>
        public static string Then_Label {
            get {
                return ResourceManager.GetString("Then_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validation Rules.
        /// </summary>
        public static string Validation_Rules_Label {
            get {
                return ResourceManager.GetString("Validation_Rules_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validation Rules.
        /// </summary>
        public static string Validation_Rules_Tab_Header {
            get {
                return ResourceManager.GetString("Validation_Rules_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When.
        /// </summary>
        public static string When_Label {
            get {
                return ResourceManager.GetString("When_Label", resourceCulture);
            }
        }
    }
}
