//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAvalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectAvalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Checkbox.
        /// </summary>
        public static string Add_Checkbox_ToolTip {
            get {
                return ResourceManager.GetString("Add_Checkbox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        public static string Add_Condition_ToolTip {
            get {
                return ResourceManager.GetString("Add_Condition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Add_Folder_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Add_Folder_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Item to Add to Project.
        /// </summary>
        public static string Add_Item_Dialog_Caption {
            get {
                return ResourceManager.GetString("Add_Item_Dialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Report Item.
        /// </summary>
        public static string Add_Item_ToolTip {
            get {
                return ResourceManager.GetString("Add_Item_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Law.
        /// </summary>
        public static string Add_Law_ToolTip {
            get {
                return ResourceManager.GetString("Add_Law_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Option.
        /// </summary>
        public static string Add_Option_ToolTip {
            get {
                return ResourceManager.GetString("Add_Option_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Options.
        /// </summary>
        public static string Add_Options_ToolTip {
            get {
                return ResourceManager.GetString("Add_Options_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Result.
        /// </summary>
        public static string Add_Result_ToolTip {
            get {
                return ResourceManager.GetString("Add_Result_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rule.
        /// </summary>
        public static string Add_Rule_ToolTip {
            get {
                return ResourceManager.GetString("Add_Rule_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Solution Item.
        /// </summary>
        public static string Add_Solution_Item_Menu_Item {
            get {
                return ResourceManager.GetString("Add_Solution_Item_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Text Item.
        /// </summary>
        public static string Add_Text_Item_ToolTip {
            get {
                return ResourceManager.GetString("Add_Text_Item_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        public static string AddItemNameLabel {
            get {
                return ResourceManager.GetString("AddItemNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettingsViewNavLabel {
            get {
                return ResourceManager.GetString("AdvancedSettingsViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearence.
        /// </summary>
        public static string AppearanceLabel {
            get {
                return ResourceManager.GetString("AppearanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto copy.
        /// </summary>
        public static string AutoCopyBehaviorLabel {
            get {
                return ResourceManager.GetString("AutoCopyBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest version automatically.
        /// </summary>
        public static string AutoDownloadLabel {
            get {
                return ResourceManager.GetString("AutoDownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto paste.
        /// </summary>
        public static string AutoPasteBehaviorLabel {
            get {
                return ResourceManager.GetString("AutoPasteBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelActionLabel {
            get {
                return ResourceManager.GetString("CancelActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string CheckboxContainerTopicLabel {
            get {
                return ResourceManager.GetString("CheckboxContainerTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string CheckboxItemTopicLabel {
            get {
                return ResourceManager.GetString("CheckboxItemTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CheckboxItemValueLabel {
            get {
                return ResourceManager.GetString("CheckboxItemValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string CheckedValueLabel {
            get {
                return ResourceManager.GetString("CheckedValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string Company_Address_Watermark {
            get {
                return ResourceManager.GetString("Company_Address_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo Path.
        /// </summary>
        public static string Company_Logo_FilePath_Watermark {
            get {
                return ResourceManager.GetString("Company_Logo_FilePath_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Name_Watermark {
            get {
                return ResourceManager.GetString("Company_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions_Label {
            get {
                return ResourceManager.GetString("Conditions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmActionLabel {
            get {
                return ResourceManager.GetString("ConfirmActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueActionLabel {
            get {
                return ResourceManager.GetString("ContinueActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Rule.
        /// </summary>
        public static string Create_Rules_Button {
            get {
                return ResourceManager.GetString("Create_Rules_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkModeLabel {
            get {
                return ResourceManager.GetString("DarkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Mode.
        /// </summary>
        public static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string Delete_Image_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Delete_Image_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rules.
        /// </summary>
        public static string Edit_Rules_Button {
            get {
                return ResourceManager.GetString("Edit_Rules_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on GPU Acceleration.
        /// </summary>
        public static string EnabledGPULabel {
            get {
                return ResourceManager.GetString("EnabledGPULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the GPU Acceleration is enabled to render the UI. Using the GPU instead of CPU may improve performance..
        /// </summary>
        public static string EnabledGPUTooltip {
            get {
                return ResourceManager.GetString("EnabledGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Condition.
        /// </summary>
        public static string Exclude_Condition_ToolTip {
            get {
                return ResourceManager.GetString("Exclude_Condition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude File.
        /// </summary>
        public static string Exclude_File_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Exclude_File_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Folder.
        /// </summary>
        public static string Exclude_Folder_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Exclude_Folder_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Result.
        /// </summary>
        public static string Exclude_Result_ToolTip {
            get {
                return ResourceManager.GetString("Exclude_Result_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Rule.
        /// </summary>
        public static string Exclude_Rule_ToolTip {
            get {
                return ResourceManager.GetString("Exclude_Rule_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string Folder_Name_Watermark {
            get {
                return ResourceManager.GetString("Folder_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettingsViewNavLabel {
            get {
                return ResourceManager.GetString("GeneralSettingsViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        public static string Generate_Document_ToolTip {
            get {
                return ResourceManager.GetString("Generate_Document_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string GreaterOperationLabel {
            get {
                return ResourceManager.GetString("GreaterOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal or Greater Than.
        /// </summary>
        public static string GreaterThanOperationLabel {
            get {
                return ResourceManager.GetString("GreaterThanOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        public static string HasOperationLabel {
            get {
                return ResourceManager.GetString("HasOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is.
        /// </summary>
        public static string IsOperationLabel {
            get {
                return ResourceManager.GetString("IsOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Items.
        /// </summary>
        public static string ItemFormDataLabel {
            get {
                return ResourceManager.GetString("ItemFormDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law Content.
        /// </summary>
        public static string ItemLawItemContentLabel {
            get {
                return ResourceManager.GetString("ItemLawItemContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law ID.
        /// </summary>
        public static string ItemLawItemIdLabel {
            get {
                return ResourceManager.GetString("ItemLawItemIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laws.
        /// </summary>
        public static string ItemLawItemsLabel {
            get {
                return ResourceManager.GetString("ItemLawItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemNameLabel {
            get {
                return ResourceManager.GetString("ItemNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Items.
        /// </summary>
        public static string Items_Label {
            get {
                return ResourceManager.GetString("Items_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Language.
        /// </summary>
        public static string LanguageSelectorLabel {
            get {
                return ResourceManager.GetString("LanguageSelectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law Content.
        /// </summary>
        public static string Law_Body_Watermark {
            get {
                return ResourceManager.GetString("Law_Body_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law Id.
        /// </summary>
        public static string Law_Id_Watermark {
            get {
                return ResourceManager.GetString("Law_Id_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laws.
        /// </summary>
        public static string Laws_Label {
            get {
                return ResourceManager.GetString("Laws_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        public static string LessOperationLabel {
            get {
                return ResourceManager.GetString("LessOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal or Less Than.
        /// </summary>
        public static string LessThanOperationLabel {
            get {
                return ResourceManager.GetString("LessThanOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextActionLabel {
            get {
                return ResourceManager.GetString("NextActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Solution Open.
        /// </summary>
        public static string No_Solution_Open_Label {
            get {
                return ResourceManager.GetString("No_Solution_Open_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatory.
        /// </summary>
        public static string ObrigatorityLabel {
            get {
                return ResourceManager.GetString("ObrigatorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observation_Label {
            get {
                return ResourceManager.GetString("Observation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observation_Watermark {
            get {
                return ResourceManager.GetString("Observation_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep running the app on background.
        /// </summary>
        public static string onClosedBehaviorLabel {
            get {
                return ResourceManager.GetString("onClosedBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start app with windows.
        /// </summary>
        public static string onStartupBehaviorLabel {
            get {
                return ResourceManager.GetString("onStartupBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation_Label {
            get {
                return ResourceManager.GetString("Operation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Invalid.
        /// </summary>
        public static string Option_Mark_As_Invalid_MenuItem {
            get {
                return ResourceManager.GetString("Option_Mark_As_Invalid_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Label {
            get {
                return ResourceManager.GetString("Options_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print_Document_ToolTip {
            get {
                return ResourceManager.GetString("Print_Document_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Document.
        /// </summary>
        public static string Print_Page_Title {
            get {
                return ResourceManager.GetString("Print_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string Project_Add_Folder_ToolBarItem {
            get {
                return ResourceManager.GetString("Project_Add_Folder_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Item.
        /// </summary>
        public static string Project_Item_Save_ToolBarItem {
            get {
                return ResourceManager.GetString("Project_Item_Save_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Responsable.
        /// </summary>
        public static string Project_Responsable_Watermark {
            get {
                return ResourceManager.GetString("Project_Responsable_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectViewNavLabel {
            get {
                return ResourceManager.GetString("ProjectViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Checkbox.
        /// </summary>
        public static string Remove_Checkbox_ToolTip {
            get {
                return ResourceManager.GetString("Remove_Checkbox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group.
        /// </summary>
        public static string Remove_Group_ToolTip {
            get {
                return ResourceManager.GetString("Remove_Group_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string Rename_File_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Rename_File_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string Rename_Folder_Item_Menu_Header {
            get {
                return ResourceManager.GetString("Rename_Folder_Item_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string Report_Date_Calendar_Header {
            get {
                return ResourceManager.GetString("Report_Date_Calendar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Code.
        /// </summary>
        public static string Report_State_Watermark {
            get {
                return ResourceManager.GetString("Report_State_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Email Address.
        /// </summary>
        public static string Responsable_Mail_Address_Watermark {
            get {
                return ResourceManager.GetString("Responsable_Mail_Address_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Phone Number.
        /// </summary>
        public static string Responsable_Phone_Number_Watermark {
            get {
                return ResourceManager.GetString("Responsable_Phone_Number_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart App.
        /// </summary>
        public static string RestartAppLabel {
            get {
                return ResourceManager.GetString("RestartAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be commited after restarting the application..
        /// </summary>
        public static string RestartNotificationLabel {
            get {
                return ResourceManager.GetString("RestartNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Solution Item.
        /// </summary>
        public static string Search_Solution_Items_Watermark {
            get {
                return ResourceManager.GetString("Search_Solution_Items_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search settings / advanced features
        ///.
        /// </summary>
        public static string SearchBoxLabel {
            get {
                return ResourceManager.GetString("SearchBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages appearence, and other settings.
        /// </summary>
        public static string SettingsPageCaption {
            get {
                return ResourceManager.GetString("SettingsPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageLabel {
            get {
                return ResourceManager.GetString("SettingsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsViewNavLabel {
            get {
                return ResourceManager.GetString("SettingsViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App is shutting down.
        /// </summary>
        public static string ShutdownDialogTitleLabel {
            get {
                return ResourceManager.GetString("ShutdownDialogTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting everything down to finished the application..
        /// </summary>
        public static string ShutdownMessagePart1 {
            get {
                return ResourceManager.GetString("ShutdownMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may take some time to be finished. Please, wait....
        /// </summary>
        public static string ShutdownMessagePart2 {
            get {
                return ResourceManager.GetString("ShutdownMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipActionLabel {
            get {
                return ResourceManager.GetString("SkipActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Solution.
        /// </summary>
        public static string Solution_Create_ToolBarItem {
            get {
                return ResourceManager.GetString("Solution_Create_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string Solution_Explorer_Label {
            get {
                return ResourceManager.GetString("Solution_Explorer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Location.
        /// </summary>
        public static string Solution_Folder_Watermark {
            get {
                return ResourceManager.GetString("Solution_Folder_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Name.
        /// </summary>
        public static string Solution_Name_Watermark {
            get {
                return ResourceManager.GetString("Solution_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solution.
        /// </summary>
        public static string Solution_Open_ToolBarItem {
            get {
                return ResourceManager.GetString("Solution_Open_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Solution.
        /// </summary>
        public static string Solution_Print_ToolBarItem {
            get {
                return ResourceManager.GetString("Solution_Print_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Report Template.
        /// </summary>
        public static string Template_Edit_Create_Item_ToolBarItem {
            get {
                return ResourceManager.GetString("Template_Edit_Create_Item_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Report Template.
        /// </summary>
        public static string Template_Edit_Open_ToolBarItem {
            get {
                return ResourceManager.GetString("Template_Edit_Open_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report Template.
        /// </summary>
        public static string Template_Edit_Save_Item_ToolBarItem {
            get {
                return ResourceManager.GetString("Template_Edit_Save_Item_ToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template_Tab_Header {
            get {
                return ResourceManager.GetString("Template_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Edit.
        /// </summary>
        public static string TemplateEditViewNavLabel {
            get {
                return ResourceManager.GetString("TemplateEditViewNavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement unit.
        /// </summary>
        public static string TextBoxItemMeasurementUnitLabel {
            get {
                return ResourceManager.GetString("TextBoxItemMeasurementUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string TextBoxItemTopicLabel {
            get {
                return ResourceManager.GetString("TextBoxItemTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme is changing... Please Wait....
        /// </summary>
        public static string ThemeChangingLabel {
            get {
                return ResourceManager.GetString("ThemeChangingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark, Light, Theme.
        /// </summary>
        public static string ThemeKeyWords {
            get {
                return ResourceManager.GetString("ThemeKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        public static string Then_Label {
            get {
                return ResourceManager.GetString("Then_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unckecked.
        /// </summary>
        public static string UncheckedValueLabel {
            get {
                return ResourceManager.GetString("UncheckedValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Rules.
        /// </summary>
        public static string Validation_Rules_Label {
            get {
                return ResourceManager.GetString("Validation_Rules_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Rules.
        /// </summary>
        public static string Validation_Rules_Tab_Header {
            get {
                return ResourceManager.GetString("Validation_Rules_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Check.
        /// </summary>
        public static string ValueCheckLabel {
            get {
                return ResourceManager.GetString("ValueCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string When_Label {
            get {
                return ResourceManager.GetString("When_Label", resourceCulture);
            }
        }
    }
}
