<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>portable</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>embedded</DebugType>
    </PropertyGroup>
    <PropertyGroup>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="QuestPDF" />
        <PackageReference Include="SkiaSharp"  />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Shared\Common\Common.csproj" />
        <ProjectReference Include="..\..\ProjectItemsReader\XmlDatasource\XmlDatasource.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Resources\Logo.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
