<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
         <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>


    <ItemGroup>
        <Folder Include="ProjectItems\Mappers\"/>
        <Folder Include="ProjectItems\Services\"/>
        <Folder Include="Solution\Mappers\"/>
        <Folder Include="Solution\Services\"/>
        <Folder Include="ValidationRules\Mappers\"/>
        <Folder Include="ValidationRules\Services\"/>
    </ItemGroup>

</Project>
